### PR TITLE
Add another recursive way in "Functional Go programmer" section

### PR DESCRIPTION
**Pull request by manhdaovan**
Should use this one for existing "Functional Go programmer"? :D

### CODE REVIEW

**Comment by abatilo** [comment]
Would you mind explaining what makes this a compiler optimized solution?

**Comment by manhdaovan** [comment]
@abatilo 

Go doesn't support tail call optimization, so this `compiler optimized` is my mistake. Sorry about that.

https://github.com/golang/go/issues/16798
https://github.com/golang/go/issues/22624#issuecomment-465321824

**Comment by abatilo** [comment]
Since it isn't compiler optimized, should this PR just be closed?

**Comment by manhdaovan** [comment]
Yes. Close it.

**Pull request closed without merging**
